### ISSUE TITLE
Cannot serialize Line Breaks from Prismic UI

### ISSUE THREAD

**Issue by Martaver** [prismicio/prismic-richtext#1]
We are using the V2 API and associated libraries.

If our writers use `shift enter` to create a line break in the rich text editor, the line break is persisted in the Prismic UI, but not in the text rendered in our front-end.

The line is included in the response from the API as `\n` embedded in the field's text. This should be interpreted as a <br/>.

**Comment by arnaudlewis** [comment]
Sorry for the late resoonse, but it's fixed in prismic-reactjs and prismic-dom but this lib should remains generic so we can't serialize \n here. If you have any question of this subject, don't hesitate to reach out to me.
