### ISSUE TITLE
Sooo huge

### ISSUE THREAD

**Issue by Tuch** [prismicio/prismic-richtext#16]
In first I love what are you're doing. Thank you guys. But I have one little question about the size of package. Size of react-dom ~29kb gzip, size of prismic-richtext ~17kb gzip.. It could be ok, but this is just a 'markup->html' library.. And I can't disable something here.. Mb we can optimize it? Or mb you can suggest something lighter?

**Comment by jdwillemse** [comment]
There is an outdated PR that should solve this. Not sure why nothing is happening there:
https://github.com/prismicio/prismic-richtext/pull/14

**Comment by nhardy** [comment]
:+1: I would also like to see some movement on the issue as `prismic-richtext` is significantly increasing bundle size.

**Comment by tpbowden** [comment]
I have created a new PR which hopefully solves this: https://github.com/prismicio/prismic-richtext/pull/19

**Comment by timReynolds** [comment]
@arnaudlewis Are you able to release 1.0.0 to NPM? I can see you've labeled it here but it's not in the registry. 

Thanks

**Comment by arnaudlewis** [comment]
All good @timReynolds ;)

**Comment by timReynolds** [comment]
🎉 

Thanks, now I've only got myself to blame for my page size.

Before
![screenshot 2019-02-05 at 19 21 32](https://user-images.githubusercontent.com/168870/52338112-5e7b8d00-2a01-11e9-8a46-cd9526d4d870.png)

After
![screenshot 2019-02-06 at 11 19 58](https://user-images.githubusercontent.com/168870/52338095-558abb80-2a01-11e9-88de-1a66af60b07d.png)

**Comment by timReynolds** [comment]
Ok I spoke too soon, seems this now errors when being server rendered due to assuming window. 

```
(node:35436) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at Object.<anonymous> (/node_modules/prismic-richtext/dist/prismic-richtext.min.js:1:230)
```

In the middle of something else right now, will investigate this later in-depth

**Comment by tpbowden** [comment]
@arnaudlewis @timReynolds Fix for the issue is here https://github.com/prismicio/prismic-richtext/pull/20
