### ISSUE TITLE
package.json does not specify path to typings

### ISSUE THREAD

**Issue by nhardy** [prismicio/prismic-richtext#17]
`package.json` should specify a `"types": "./d.ts/index.d.ts",` property so that consuming TypeScript applications have correct typings

**Comment by nhardy** [comment]
I also note that `d.ts/index.d.ts` is empty because `module.exports` is used instead of `export default`.

**Comment by lihbr** [comment]
Hey @nhardy, I'm really sorry we failed to give you any attention back then.

We're currently reworking this kit, once of the goal being to ship it with proper TypeScript support.

This issue will be fixed soon.

**Comment by lihbr** [comment]
Fixed in v2 🎉
