### ISSUE TITLE
Publish latest versions to npm

### ISSUE THREAD

**Issue by TrySound** [prismicio/prismic-richtext#32]
These two version were not published on npm
![image](https://user-images.githubusercontent.com/5635476/87650926-123a8d80-c75b-11ea-803b-3c91b8e56ab9.png)

The latest is 1.0.3
https://www.npmjs.com/package/prismic-richtext

**Comment by TrySound** [comment]
cc @hypervillain

**Comment by TrySound** [comment]
Friendly ping @hypervillain @arnaudlewis @srenault

**Comment by lihbr** [comment]
Hi @TrySound, sorry for the delay! I'll reach out to them and try to get those versions published~ 💪

**Comment by TrySound** [comment]
Hi @lihbr, any luck?

**Comment by lihbr** [comment]
Hey @TrySound, it's now live 🎉 you can use version `1.1.0`, although we moved the package to our NPM organisation, new package name is: `@prismicio/richtext`, let me know if everything's ok for you now so we can close this issue 🙂

**Comment by TrySound** [comment]
Awesome, thanks!

**Comment by TrySound** [comment]
Though this is a dependency of prismic-reactjs we use which is not in org yet.

**Comment by lihbr** [comment]
You're right, we're updating this afternoon `prismic-reactjs` and `prismic-dom` to use this new dependency, we plan later on on moving all dependencies still out of the organization to it, but this will require more care as those dependencies name are mentioned pretty much everywhere across our documentation.
