### ISSUE TITLE
TypeError: t.elected is undefined

### ISSUE THREAD

**Issue by tjbp** [prismicio/prismic-richtext#49]
When running `PrismicDOM.RichText.asHtml` with body items fetched via GraphQL I receive the error in the title - it seems to be coming from [here](https://github.com/prismicio/prismic-richtext/blob/5c0a5ea33beba21adead113b9513392371e28f0c/src/tree.ts#L72). It can be tested using the following (object is an example returned from the endpoint):

```js
PrismicDOM.RichText.asHtml([
  {
    spans: Array(1),
    text: "Testing <a href=\"https://www.example.com/\" target=\"\">example</a> link",
    type: "paragraph"
  }
], () => '/')
```

**Comment by lihbr** [comment]
Hey there, sorry for the lack of response, should be fixed with the new kits (`@prismicio/helpers^2`, replacing `prismic-dom`), feel free to reopen if needed.
