### ISSUE TITLE
Accept a Link Resolver to pre-process a `hyperlink` span's URL

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/prismic-richtext#56]
### Is your feature request related to a problem? Please describe.

`@prismicio/helpers`'s `asHTML()` helper optionally accepts a Link Resolver and an HTML Serializer.

```typescript
asHTML(richTextValue, linkResolver, htmlSerializer)
```

- `linkResolver`: Used in the default HTML Serializer to serialize `hyperlink` spans.
- `htmlSerializer`: Used to override the default HTML Serializer.

If the provided HTML Serializer serializes `hyperlink` blocks, the provided Link Resolver is ignored. One would need to reference the Link Resolver manually some how, such as re-importing. Furthermore, one would need to understand how to use `asLink()` with a `hyperlink` span to compute the URL.

> ```typescript
> import * as prismicH from '@prismicio/helpers'
> import { linkResolver } from '../prismicio'
> 
> const htmlSerializer = {
>   hyperlink: ({ node, children }) => {
>     const url = prismicH.asLink(node.data, linkResolver)
> 
>     if (url) {
>       return `<a href="${prismicH.asLink(}" class="link">${children}</a>`
>     }
>   }
> }
> ```
>
> _Passing `node.data` to `asLink()` is unintuitive._

As a final downside to this specific situation, one cannot nicely omit a Link Resolver in this case because `linkResolver` and `htmlSerializer` are positional parameters.

> ```typescript
> asHTML(richTextValue, undefined, htmlSerializer)
> ```
> _Passing `undefined` to the `linkResolver` parameter is ugly and unclear._

### Describe the solution you'd like

If `@prismicio/richtext`'s `serialize()` function accepted a Link Resolver, it could pre-process `hyperlink` spans to automatically compute the span's URL. This means HTML Serializers implementing a `hyperlink` serializer would not need to use Link Resolvers directly.

An HTML Serializer could now look like this:

```typescript
const htmlSerializer = {
  hyperlink: ({ children, node }) => {
    if (node.url) {
      return `<a href="${node.url}" class="link">${children}</a>`
    }
  }
}
```

In order to populate the `url` property, `@prismicio/richtext` would need to treat `hyperlink` as a special case.

Note that `node.url` is injected by `@prismicio/richtext` and does not come directly from the Rich Text block. Adding to `node` rather than a new parameter is necessary to support function HTML Serializers (otherwise, a new parameter would need to be added — a breaking change).

### Describe alternatives you've considered

`@prismicio/react` skirts around this issue by implementing links using `<PrismicLink>`. `<PrismicLink>` has access to a globally configured Link Resolver via `<PrismicProvider>`, thus it does not need to re-import a Link Resolver or manually call `asLink()` in a `hyperlink` serializer.

While this works for `@prismicio/react`, it is an unintentional benefit and should not be replicated for generalized applications. Setting a Link Resolver on `window`, for example, would be a bad idea.

### Additional context

Thanks to @samlfair for surfacing this issue. 🙂

**Comment by lihbr** [comment]
Makes sense to me! ☺️

**Comment by angeloashmore** [comment]
With the push to replace Link Resolver with Route Resolver, let's close this request. We can revisit it if the need arises in the future.
